jasypt:
   encryptor:
      password: ${jasyptpwd:secretkey}
      algorithm: PBEWithMD5AndDES

server:
   port: 8085
   servlet:
      context-path: /university-service
      session:
         timeout: 21600s

spring:
   datasource:
      driver-class-name: org.h2.Driver
      jdbcUrl: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
      username: sa
      password:
      hikari:
         poolName: pool
